<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


?>
<div id="quote_history_block" class="edit-quote-comments">
    <?php if ($block->canAddComment()) : ?>
        <div class="quote-history-block" id="history_form">

            <div class="admin__field">
                <label for="history_status" class="admin__field-label"><?php echo __('Status') ?></label>

                <div class="admin__field-control">
                    <select name="history[status]" id="history_status" class="admin__control-select">
                        <?php foreach ($block->getStatuses() as $_code => $_label) : ?>
                            <option value="<?php echo $_code ?>"
                                <?php if ($_code == $block->getQuote()->getStatus()) : ?>
                                    selected="selected"
                                <?php endif; ?>>
                                <?php echo $_label ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="admin__field">
                <label for="history_comment" class="admin__field-label">
                    <?php echo __('Comment') ?>
                </label>

                <div class="admin__field-control">
                    <textarea name="history[comment]"
                              rows="3"
                              cols="5"
                              id="history_comment"
                              class="admin__control-textarea"></textarea>
                </div>
            </div>

            <div class="admin__field">
                <div class="quote-history-comments-options">
                    <div class="admin__field admin__field-option">
                        <?php if ($block->canSendCommentEmail()) : ?>
                            <input name="history[is_customer_notified]"
                                   type="checkbox"
                                   id="history_notify"
                                   class="admin__control-checkbox"
                                   value="1"/>
                            <label class="admin__field-label" for="history_notify">
                                <?php echo __('Notify Customer by Email') ?>
                            </label>
                        <?php endif; ?>
                    </div>

                    <div class="admin__field admin__field-option">
                        <input name="history[is_visible_on_front]"
                               type="checkbox"
                               id="history_visible"
                               class="admin__control-checkbox"
                               value="1"/>
                        <label class="admin__field-label" for="history_visible">
                            <?php echo __('Visible on Storefront') ?>
                        </label>
                    </div>
                </div>

                <div class="quote-history-comments-actions">
                    <?php echo $block->getChildHtml('submit_button') ?>
                </div>
            </div>
        </div>
    <?php endif; ?>

    <ul class="note-list">
        <?php foreach ($block->getQuote()->getStatusHistoryCollection(true) as $_item) : ?>
            <li class="note-list-item">
                <span class="note-list-date">
                    <?php echo $block->formatDate(
                        $_item->getCreatedAtDate(),
                        \IntlDateFormatter::MEDIUM
                    ) ?>
                </span>
                <span class="note-list-time">
                    <?php echo $block->formatTime(
                        $_item->getCreatedAtDate(),
                        \IntlDateFormatter::MEDIUM
                    ) ?>
                </span>
                <span class="note-list-status"><?php echo $_item->getStatusLabel() ?></span>
                <span class="note-list-customer">
                <?php echo __('Customer') ?>
                    <?php if ($block->isCustomerNotificationNotApplicable($_item)) : ?>
                        <span class="note-list-customer-notapplicable">
                            <?php echo __('Notification Not Applicable') ?>
                        </span>
                    <?php elseif ($_item->getIsCustomerNotified()) : ?>
                        <span class="note-list-customer-notified">
                            <?php echo __('Notified') ?>
                        </span>
                    <?php else : ?>
                        <span class="note-list-customer-not-notified">
                            <?php echo __('Not Notified') ?>
                        </span>
                    <?php endif; ?>
            </span>
                <?php if ($_item->getComment()) : ?>
                    <div class="note-list-comment">
                        <?php echo $block->escapeHtml(
                            $_item->getComment(),
                            ['b', 'br', 'strong', 'i', 'u', 'a']
                        ) ?>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script>
        require(['prototype'], function () {

            if ($('quote_status')) $('quote_status').update('<?php echo $block->getQuote()->getStatusLabel() ?>');

        });
    </script>
</div>
