<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<script>
    require([
        "prototype",
        "Cart2Quote_Quotation/quote/view/form",
        "Magento_Catalog/catalog/product/composite/configure",
        "domReady!"
    ], function () {
        //quote.sidebarHide();
        function initProductConfigure() {
            productConfigure.addListType('product_to_add', {
                urlFetch: '<?php echo $block->getUrl('quotation/quote_view/configureProductToAdd') ?>'
            });

            productConfigure.addListType('quote_items', {
                urlFetch: '<?php echo $block->getUrl('quotation/quote_view/configureQuoteItems') ?>'
            });
        }

        Event.observe(window, 'load', function () {
            if (window.productConfigure) {
                initProductConfigure();
            }
        });

        if (window.productConfigure) {
            initProductConfigure();
        }
    });
</script>
