<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<div class="admin__field field-comment ">
    <th><label for="quote-status" class="admin__field-label"><span><?php echo __('Quote Status') ?></span></label></th>
    <td>
        <div class="admin__field-control">
            <span id="quote_status">
                <select class=" select admin__control-select" id="quote_status" name="quote[status]">
                    <?php foreach ($block->getAllStatussesAsArray() as $status) : ?>
                        <?php
                        $flag = '';
                        if ($block->getStatusLabel() == $status['label']) {
                            $flag = 'selected';
                        }
                        ?>
                        <option <?php echo $flag; ?> value="<?php echo $status['value']; ?>">
                            <?php echo $status['label']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </span>
        </div>
    </td>
</div>
