<?php
/**
 * CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<?php
$quote = $block->getQuote();
$isActiveReminderDate = $block->isActiveReminderDate();
?>
<div class="admin__field field-comment ">
    <th>
        <label for="quote-reminder-date" class="admin__field-label">
            <span><?php echo __('Reminder Date') ?></span>
        </label>
    </th>
    <td>
        <div class="admin__field-control">
            <span id="reminder_date_wrap" class="datebox-datepicker">
                <input type="text"
                       id="reminder_date"
                       class="input-text admin__control-text no-changes _has-datepicker"
                       name="quote[reminder_date]"
                       value="<?php echo $quote->getReminderDate(); ?>"
                    <?php echo $isActiveReminderDate; ?>/>
                <button type="button" style="display:none;"
                        class="ui-datepicker-trigger reminder-trigger v-middle" <?php echo $isActiveReminderDate; ?>>
                    <span>Reminder Date</span>
                </button>
            </span>
            <div class="admin__actions-switch" data-role="switcher">
                <input id="quote-reminder-switch"
                       name="quote[reminder_enabled]"
                       type="checkbox"
                       class="admin__actions-switch-checkbox"
                       value="1"
                    <?php if ($quote->getReminderEnabled()) : ?>
                        checked
                    <?php endif; ?>
                />
                <label class="admin__actions-switch-label"
                       for="quote-reminder-switch">
                    <span class="admin__actions-switch-text"
                          data-text-on="Yes" data-text-off="No"></span>
                </label>
                <div class="switcher-caption"><?php echo __('[send reminder email]') ?></div>
            </div>
        </div>
    </td>
</div>
<script type="text/javascript">
    require(["jquery", "jquery/ui"], function ($) {
        $(document).ready(function () {
            $("#reminder_date").datepicker({dateFormat: "yy-mm-dd"});
            $(".reminder-trigger").removeAttr("style");
            $(".reminder-trigger").click(function () {
                $("#reminder_date").focus();
            });
        });
    });
</script>
