<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block Cart2Quote\Quotation\Block\Quote\Email\Button */
?>
<table class="button checkout-button-container" width="100%" border="0" cellspacing="0" cellpadding="0" align="right">
    <tr>
        <td class="checkout-button-container-row">
            <table class="inner-wrapper" width="" align="right" border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td class="checkout-button-container-row-background">
                        <a target="_blank" class="button" href="<?php echo $block->getUrlForCheckoutButton(); ?>">
                            <span><?php echo $block->getFrontendButtonLabel(); ?></span>
                        </a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<?php if (!$block->customerIsGuest()) : ?>
    <table align="right" border="0" cellspacing="0" cellpadding="0" class="custom-dashboard-button">
        <tr class="custom-dashboard-button-row">
            <td align="right" class="custom-dashboard-button-column">
                <a target="_blank" class="button" href="<?php echo $block->getMoreOptionsUrl(); ?>">
                    <span><?php echo __('Or click here for more options'); ?></span>
                </a>
            </td>
        </tr>
    </table>
<?php endif; ?>
