<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block Cart2Quote\Quotation\Block\Quote\Email\Items */
?>
<?php
$_quote = $block->getQuote();
?>
<?php if ($_quote) : ?>
    <?php $_items = $_quote->getAllItems(); ?>
    <table class="email-items">
        <?php foreach ($block->getSections() as $section) : ?>
            <?php $sectionsItems = $block->getQuote()->getSectionItems($section->getSectionId()); ?>
            <?php if (count($sectionsItems) > 0) : ?>
                <thead>
                <?php if (!empty($section->getLabel())) : ?>
                    <tr class="section-heading">
                        <th colspan="5">
                            <h2><b><?php echo $section->getLabel(); ?></b></h2>
                        </th>
                    </tr>
                <?php endif; ?>
                <tr>
                    <th class="item-info" colspan="2">
                        <?php echo __('Items'); ?>
                    </th>
                    <th class="item-qty">
                        <?php echo __('Qty'); ?>
                    </th>
                    <th class="item-price">
                        <?php echo __('Quoted Price'); ?>
                    </th>
                    <th class="item-price">
                        <?php echo __('Row Total'); ?>
                    </th>
                </tr>
                <?php if ($_quote->hasOptionalItems()) : ?>
                    <tr>
                        <th colspan="5">
                            <span style="font-weight:normal; font-size:smaller;">
                                <?= __('Products with * are optional') ?>
                            </span>
                        </th>
                    </tr>
                <?php endif; ?>
                </thead>
                <?php foreach ($sectionsItems as $item) : ?>
                    <?php if ($item->getParentItem()) : ?>
                        <?php continue; ?>
                    <?php endif; ?>
                    <tbody>
                    <?php echo $block->getItemHtml($item) ?>
                    </tbody>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
        <?php echo $block->getChildHtml('quote_totals') ?>
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed(
        'quote',
        $_quote,
        $_quote->getStore()
    ) && $_quote->getGiftMessageId()
    ) : ?>
        <?php
        $_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
        $_giftMessage = $_giftMessageHelper->getGiftMessage($_quote->getGiftMessageId()); ?>
        <?php if ($_giftMessage) : ?>
            <br/>
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo __('Gift Message for this Quote') ?></h3>
                        <strong>
                            <?php echo __('From:'); ?>
                        </strong>&nbsp;<?php echo $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/>
                        <strong>
                            <?php echo __('To:'); ?>
                        </strong>&nbsp;<?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong>
                            <?php echo __('Message:'); ?>
                        </strong>
                        <br/><?php echo $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
