<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
/** @var \Cart2Quote\Quotation\Block\Quote\Email\Items\Quote\Column $block */
/** @var $thumbnailHelper \Cart2Quote\Quotation\Helper\ProductThumbnail */
$thumbnailHelper = $this->helper('Cart2Quote\Quotation\Helper\ProductThumbnail');
?>

<?php if ($block->getItem()->getParentItem()) : ?>
    <tr class="options-label">
        <?php $attributes = json_decode(
            $block->getItem()->getOptionByCode('bundle_selection_attributes')->getValue(),
            true
        ); ?>
        <td class="col label options-label-content" colspan="5"><?php echo $attributes['option_label']; ?></td>
    </tr>
<?php endif; ?>

<?php
$class = '';
if (($block->getIndex() == $block->getCount() - 1)) {
    $class .= ' last-element';
}
if ($block->getItem()->getParentItem()) {
    $class .= ' item-options-container';
} else {
    $class .= ' item-parent';
}
?>
<tr id="order-item-row-<?php echo $block->getItem()->getItemId() ?>"
    class="<?php echo $class ?>"
    <?php if ($block->getItem()->getParentItem()) : ?>
        data-th="<?php echo $block->getItem()->getName() ?>"
    <?php endif; ?>>
    <?php if (!$block->getItem()->getParentItem()) : ?>
        <td class="col name" colspan="1" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
            <?php if ($thumbnailHelper->showProductThumbnailProposal()): ?>
                <?php $item = $block->getItem(); ?>
                <?php $product = $item->getProduct(); ?>
                <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $item->getName(); ?>">
                    <img class="product-thumbnail" align="left"
                         src="<?php echo $thumbnailHelper->getProductThumbnail($product)?>" width="75"
                         height="75" alt="<?php echo $item->getName(); ?>"
                         title="<?php echo $item->getName(); ?>"/>
                </a>
            <?php endif; ?>
            <strong class="product name product-item-name"><?php echo $block->getItem()->getName(); ?>
                <?php if ($block->getItem()->getCurrentTierItem()->getMakeOptional()) : ?>
                    <?= " *" ?>
                <?php endif; ?>
            </strong>
            <p class="sku"><?php echo __('SKU'); ?>: <?php echo $block->escapeHtml($block->getItem()->getSku()); ?></p>
        </td>
        <td colspan="4">
            <table class="item-details">
                <tr>
                    <?php echo $block->getParentBlock()->getChildBlock('quote.email.columns.item-info')->getChildHtml('', $useCache = false); ?>
                </tr>
            </table>
        </td>
    <?php else : ?>
        <td class="col value value-padding" colspan="5"
            data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
            <?php echo $block->escapeHtml($block->getItem()->getQty() . ' x ' . $block->getItem()->getName()); ?>
            <span class="price">
                    <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency(
                        $block->getItem()->getCurrentTierItem()->getCustomPrice(),
                        true,
                        false
                    ); ?>
            </span>
        </td>
    <?php endif; ?>
</tr>