<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<?php /** @var $block \Cart2Quote\Quotation\Block\Quote\Success */ ?>
<div class="quotation-success">
    <?php if ($block->getQuoteId()) : ?>
        <?php if ($block->getCanViewQuote()) : ?>
            <p><?php echo sprintf(
                    '%s <a href="%s" class="quote-number"><strong>%s</strong></a>',
                    __('Your quote request number is:'),
                    $block->escapeHtml($block->getViewQuoteUrl()),
                    $block->escapeHtml($block->getQuoteId())
                ); ?></p>

        <?php else : ?>
            <?php $realQuoteId = $block->escapeHtml($block->getQuoteId()); ?>
            <p><?php echo sprintf("%s: <span>%s</span>.",
                    __('Your quote request number is'),
                    $realQuoteId) ?></p>
        <?php endif; ?>
        <p><?php echo __('We will email you a quote request confirmation with details.') ?></p>
    <?php endif; ?>
    <?php echo $block->getAdditionalInfoHtml() ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               title="<?php echo __('Continue Shopping') ?>"
               href="<?php echo $block->getUrl() ?>">
                <span><?php echo __('Continue Shopping') ?></span>
            </a>
        </div>
    </div>
</div>
