<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var \Cart2Quote\Quotation\Block\Quote\Item\Renderer\Column $block */

?>
<td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" colspan="3">
    <strong class="product name product-item-name">
        <?php echo $block->escapeHtml($block->getItem()->getName()) ?>
    </strong>
    <?php if ($options = $block->getOptionList()) : ?>
        <dl class="item-options">
            <?php foreach ($options as $option) : ?>
                <dt><?php echo $block->escapeHtml($option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()) : ?>
                    <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                    <dd>
                        <?php if (isset($formatedOptionValue['full_view'])) : ?>
                            <?php echo $formatedOptionValue['full_view'] ?>
                        <?php else : ?>
                            <?php echo $formatedOptionValue['value'] ?>
                        <?php endif; ?>
                    </dd>
                <?php else : ?>
                    <dd>
                        <?php
                        if ((isset($option['print_value']))) {
                            $optionValue = $option['print_value'];
                        } else {
                            $optionValue = $option['value'];
                        } ?>
                        <?php echo nl2br($block->escapeHtml($optionValue)) ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
    <?php if ($addtInfoBlock) : ?>
        <?php echo $addtInfoBlock->setItem($block->getItem())->toHtml(); ?>
    <?php endif; ?>
    <?php if ($block->getItem()->getDescription()) : ?>
        <p><strong><?php echo $block->escapeHtml(__('Comment:')); ?></strong><br />
            <?php echo $block->escapeHtml($block->getItem()->getDescription()) ?></p>
    <?php endif; ?>
</td>