<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildren()); ?>
<?php $_count = count($items) ?>
<?php $_item = $block->getItem() ?>

<?php foreach ($items as $index => $_item) : ?>
    <?php $_quote = $_item->getQuote() ?>
    <?php echo $block->getParentBlock()->getChildBlock('bundle.items.columns')
        ->setItem($_item)
        ->setQuote($_quote)
        ->setCount($_count)
        ->setIndex($index)
        ->getChildHtml('', $useCache = false) ?>
<?php endforeach;
