<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Quote\Email\Items\DefaultItems */

/** @var $_item \Magento\Quote\Model\Quote\Item */
/** @var $_quote \Cart2Quote\Quotation\Model\Quote */
$_item = $block->getItem();
$_quote = $_item->getQuote();
?>
<tr>
    <?php echo $block->getParentBlock()->getChildBlock('default.items.columns')
        ->setItem($_item)
        ->setQuote($_quote)
        ->getChildHtml('', $useCache = false) ?>
</tr>
<?php
$_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
if ($_item->getGiftMessageId() && $_giftMessage = $_giftMessageHelper->getGiftMessage($_item->getGiftMessageId())) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo __('Gift Message') ?></h3>
                        <strong><?php echo __('From:'); ?></strong>&nbsp<?php echo $block->escapeHtml(
                            $_giftMessage->getSender()
                        ) ?>
                        <br/><strong><?php echo __('To:'); ?></strong>&nbsp<?php echo $block->escapeHtml(
                            $_giftMessage->getRecipient()
                        ) ?>
                        <br/><strong><?php echo __('Message:'); ?></strong>
                        <br/><?php echo $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
