<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
/** @var \Cart2Quote\Quotation\Block\Quote\Item\Renderer\Column $block */

?>
<?php if ($block->getItem()->getParentItem()) : ?>
    <tr class="options-label">
        <?php $attributes = json_decode(
            $block->getItem()->getOptionByCode('bundle_selection_attributes')->getValue(),
            true
        ); ?>
        <td class="col label" colspan="8"><?php echo $attributes['option_label']; ?></td>
    </tr>
<?php endif; ?>
<tr id="order-item-row-<?php echo $block->getItem()->getItemId() ?>"
    class="<?php if ($block->getItem()->getParentItem()) : ?>
        item-options-container
    <?php else : ?>
        item-parent
    <?php endif; ?>"
    <?php if ($block->getItem()->getParentItem()) : ?>
        data-th="<?php echo $block->getItem()->getName() ?>"
    <?php endif; ?>>
<?php if (!$block->getItem()->getParentItem()) : ?>
    <td colspan="3" class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <strong class="product name product-item-name"><?php echo $block->getItem()->getName() ?></strong>
        <?php if ($block->getItem()->getDescription()) : ?>
            <p><strong><?php echo $block->escapeHtml(__('Comment:')); ?></strong><br />
                <?php echo $block->escapeHtml($block->getItem()->getDescription()) ?></p>
        <?php endif; ?>
    </td>
<?php else : ?>
    <td colspan="3" class="col value" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
        <?php echo $block->escapeHtml($block->getItem()->getQty() . ' x ' . $block->getItem()->getName()) ?>
    <?php if ($block->isHidePrices()) : ?>
        <span class="price">
        <span class="price">
        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')
                        ->currency($block->getItem()->getCurrentTierItem()->getCustomPrice(), true, false) ?>
        </span>
        </span>
        <?php endif; ?>
    </td>
<?php endif; ?>
