<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Checkout\QuoteNotice */ ?>
<?php if ($block->getQuote()->getItemsCount() > 0) : ?>
    <p>
        <?php echo __(
            'It seems that you have <b>%1</b> product(s) in your Quote list',
            $block->getQuote()->getItemsCount()
        ) ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php echo $block->getUrl('quotation/quote/index') ?>">
                <span><?php echo __('View Quote List') ?></span>
            </a>
        </div>
    </div>
    </p>
<?php endif; ?>