<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var \Cart2Quote\Quotation\Block\Quote\Email\Items\Quote\Column $block */
$item = $block->getItem();
$product = $item->getProduct();
/** @var $thumbnailHelper \Cart2Quote\Quotation\Helper\ProductThumbnail */
$thumbnailHelper = $this->helper('Cart2Quote\Quotation\Helper\ProductThumbnail');
?>

<td class="item-info <?php if ($block->getItemOptions()) {
    echo 'has-extra';
} ?>"
    colspan="1">
    <?php if ($thumbnailHelper->showProductThumbnailProposal()): ?>
    <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $item->getName(); ?>">
        <img class="product-thumbnail" align="left"
             src="<?php echo $thumbnailHelper->getProductThumbnail($product)?>" width="75"
             height="75" alt="<?php echo $item->getName(); ?>"
             title="<?php echo $item->getName(); ?>"/>
    </a>
    <?php endif; ?>
    <strong class="product-name">
        <?php echo $block->escapeHtml($block->getItem()->getName()); ?>
        <?php if ($block->getItem()->getCurrentTierItem()->getMakeOptional()) : ?>
            <?= " *" ?>
        <?php endif; ?>
    </strong>
    <p class="sku"><?php echo __('SKU'); ?>: <?php echo $block->escapeHtml($block->getSku($block->getItem())) ?></p>
    <?php if ($block->getItemOptions()) : ?>
        <dl class="item-options">
            <?php foreach ($block->getItemOptions() as $option) : ?>
                <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                <dd>
                    <?php echo nl2br($option['value']) ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock) : ?>
        <?php echo $addInfoBlock->setItem($block->getItem())->toHtml() ?>
    <?php endif; ?>
</td>
<td colspan="4">
    <table class="item-details">
        <tr>
            <?php echo $block->getParentBlock()
                ->getChildBlock('quote.email.columns.item-info')
                ->getChildHtml('',$useCache = false); ?>
        </tr>
    </table>
</td>


