<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/**
 * @var \Cart2Quote\Quotation\Block\Adminhtml\System\Config\Form\Field\Information $block
 */
?>
<div class="box">
    <p>
        <b>
            <?php echo __(
                'Cart2Quote for Magento 2 is Provided by %1',
                $block->getLink($block->getCart2QuoteUrl(), __('Cart2Quote | B2B Magento extensions'))
            ); ?>
        </b>
    </p>
    <?php echo __(
        ' For documentation and support visit %1 or contact: %2 ',
        $block->getLink($block->getCart2QuoteSupportPageUrl(), __('the Cart2Quote support page')),
        $block->getLink('mailto:support@cart2quote.com', 'support@cart2quote.com')
    ); ?>
</div>