<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $quoteButton = $block->addChild('quote_button', 'Cart2Quote\Quotation\Block\Button'); ?>
<?php $_product = $block->getProduct() ?>
<?php if (($_product->isSaleable() || $quoteButton->showQuoteButton()) && $block->hasOptions()) : ?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary customize"
                type="button">

            <?php if ($_product->isSaleable() && !$quoteButton->showQuoteButton()) : ?>
                <span><?php echo __('Customize and Add to Cart'); ?></span>
            <?php elseif (!$_product->isSaleable() && $quoteButton->showQuoteButton()) : ?>
                <span><?php echo __('Customize and Add to Quote'); ?></span>
            <?php else : ?>
                <span><?php echo __('Customize'); ?></span>
            <?php endif; ?>

        </button>
    </div>
<?php endif; ?>
