<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Info */
?>

<div class="admin__page-section-item quote-comment">
    <br/>
    <div class="admin__field field-comment ">
        <label for="quote-comment" class="admin__field-label"><span><?php echo __('Quote Comments') ?></span></label>

        <div class="admin__field-control">
        <textarea id="quote-comment" name="quote[comment][customer_note]"
                  class="admin__control-textarea"><?php echo $block->escapeHtml($block->getCommentNote()) ?></textarea>
        </div>
    </div>
    <input type="hidden"
           id="increment_id"
           name="increment_id"
           value="<?php echo $this->getQuote()->getIncrementId(); ?>"/>
</div>