<?php
/**
 * CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 *
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


?>
<?php /** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\SelectRate */ ?>
<?php if ($block->getCustomerId()) : ?>
    <tr>
        <th>
            <label class="admin__field-label" for="currency_switcher">
                <?php echo __('Quote Currency:') ?>
            </label>
        </th>
        <td>
            <select id="currency_switcher"
                    class="admin__control-select"
                    name="order[currency]"
                    onchange="quote.setCurrencyId(this.value);
                    quote.setCurrencySymbol(this.options[this.selectedIndex].getAttribute('symbol'));">
                <?php foreach ($block->getAvailableCurrencies() as $code) : ?>
                    <option symbol="<?php echo $block->getCurrencySymbol($code) ?>"
                            value="<?php /* @escapeNotVerified */ echo $code ?>"
                        <?php if ($code == $block->getQuoteCurrencyCode()) : ?>
                            selected="selected"
                        <?php endif ?>
                    >
                        <?php echo $block->getCurrencyName($code) ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </td>
    </tr>
<?php
endif;
