<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/**
 * @var $block Cart2Quote\Quotation\Block\Adminhtml\System\Config\Grid\Address
 */
?>
<div id="<?php echo $this->getElement()->getHtmlId() ?>-address-grid"
     data-bind="scope:'<?php echo $this->getElement()->getHtmlId() ?>-address-grid'"
     class="address-grid">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "<?php echo $this->getElement()->getHtmlId() ?>-address-grid": {
                            "component": "Cart2Quote_Quotation/js/system/config/grid/address",
                            "data": <?php echo \Zend_Json::encode($block->getAddressGridConfig()); ?>,
                            "id": "<?php echo $this->getElement()->getHtmlId() ?>-address-grid"
                        }
                    }
                }
            }
        }
    
    </script>
</div>
