<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
/** @var $thumbnailHelper \Cart2Quote\Quotation\Helper\ProductThumbnail */

/** @var $block \Cart2Quote\Quotation\Block\Quote\Email\Items\Bundle */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildren()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>
<?php $thumbnailHelper = $this->helper('Cart2Quote\Quotation\Helper\ProductThumbnail'); ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $item) : ?>

    <?php if ($item->getOptions() || $parentItem->getDescription()) : ?>
        <?php $_showlastRow = true ?>
    <?php else : ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($item->getParentItem()) : ?>
        <tr class="options-label options-label-header">
            <?php $attributes = json_decode(
                $item->getOptionByCode('bundle_selection_attributes')->getValue(),
                true
            ); ?>
            <td class="col label" colspan="3"><?php echo $attributes['option_label']; ?></td>
        </tr>
    <?php endif; ?>
    <?php
    $class = '';
    if ($item->getParentItem()) {
        $class .= ' item-options-container';
    } else {
        $class .= ' item-parent';
    }
    ?>
    <tr id="order-item-row-<?php echo $item->getItemId() ?> item-details"
        class="<?php echo $class; ?>"
        <?php if ($item->getParentItem()) : ?>
            data-th="<?php echo $item->getName() ?>"
        <?php endif; ?>>
        <?php if (!$item->getParentItem()) : ?>
            <?php $product = $item->getProduct(); ?>
            <td class="col name" data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                <?php if ($thumbnailHelper->showProductThumbnailRequest()): ?>
                    <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $item->getName(); ?>">
                        <img class="product-thumbnail" align="left"
                             src="<?php echo $thumbnailHelper->getProductThumbnail($product) ?>" width="75"
                             height="75" alt="<?php echo $item->getName(); ?>"
                             title="<?php echo $item->getName(); ?>"/>
                    </a>
                <?php endif; ?>
                <strong class="product name product-item-name"><?php echo $item->getName() ?></strong>
                <p class="sku"><?= __('SKU'); ?>: <?php echo $block->escapeHtml($item->getSku()) ?></p>
            </td>
            <td colspan="2">
                <table class="item-details">
                    <tr>
                        <td class="item-qty" data-th="<?php echo $block->escapeHtml(__('Quantity')); ?>">
                            <?php if (!$item->getParentItem()): ?>
                                <?php echo $item->getQty(); ?>
                            <?php endif; ?>
                        </td>
                        <?php if (!$item->getParentItem()) : ?>
                            <?php if (!$block->hidePrice()) : ?>
                                <td class="item-price">
                                    <?php echo $block->getPriceHtml(); ?>
                                </td>
                            <?php endif; ?>
                        <?php endif; ?>
                    </tr>
                </table>
            </td>
        <?php else: ?>
            <td class="col value value-padding" colspan="3"
                data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>">
                <?php echo $block->escapeHtml($item->getQty() . ' x ' . $item->getName()) ?>
                <?php if (!$block->hidePrice()) : ?>
                    <span class="price">&nbsp;<?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')
                            ->currency($item->getPrice() * $item->getQty(), true, false) ?>
                    </span>
                <?php endif; ?>
            </td>
        <?php endif; ?>
    </tr>
    <?php if ($item->getDescription()) : ?>
        <tr>
            <td class="item-comment" colspan="3">
                <div class="item-comment-container">
                    <span class="product-name"><?= __('Comment'); ?></span>
                    <?php echo $block->escapeHtml($item->getDescription()); ?>
                </div>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>
