<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Quote\Email\Items\DefaultItems */

/** @var $item \Magento\Quote\Model\Quote\Item */
/** @var $thumbnailHelper \Cart2Quote\Quotation\Helper\ProductThumbnail */
$thumbnailHelper = $this->helper('Cart2Quote\Quotation\Helper\ProductThumbnail');
$item = $block->getItem();
$product = $item->getProduct();
$quote = $item->getQuote();
?>
<tr>
    <td class="item-info<?php if ($block->getItemOptions()) : ?> has-extra<?php endif; ?>">
        <?php if ($thumbnailHelper->showProductThumbnailRequest()): ?>
            <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $item->getName(); ?>">
                <img class="product-thumbnail" align="left"
                     src="<?php echo $thumbnailHelper->getProductThumbnail($product)?>" width="75"
                     height="75" alt="<?php echo $item->getName(); ?>"
                     title="<?php echo $item->getName(); ?>"/>
            </a>
        <?php endif; ?>
        <strong class="product-name"><?= $block->escapeHtml($item->getName()) ?></strong>

        <p class="sku"><?= __('SKU'); ?>: <?= $block->escapeHtml($block->getSku($item)) ?></p>
        <?php if ($block->getItemOptions()) : ?>
            <dl class="item-options">
                <?php foreach ($block->getItemOptions() as $option) : ?>
                    <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                    <dd>
                        <?php echo nl2br($option['value']) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
        <?php endif; ?>
        <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) : ?>
            <?= $addInfoBlock->setItem($item)->toHtml() ?>
        <?php endif; ?>
    </td>
    <td colspan="2">
        <table class="item-details">
            <tr>
                <td class="item-qty"><?php echo $item->getQty() * 1 ?></td>
                <?php if (!$block->hidePrice()) : ?>
                    <td class="item-price">
                        <?php echo $block->getPriceHtml(); ?>
                    </td>
                <?php endif; ?>
            </tr>
        </table>
    </td>
</tr>

<?php if ($item->getDescription()) : ?>
    <tr>
        <td class="item-comment" colspan="3">
            <div class="item-comment-container">
                <span class="product-name"><?= __('Comment'); ?></span>
                <?php echo $block->escapeHtml($item->getDescription()); ?>
            </div>
        </td>
    </tr>
<?php endif; ?>
<?php
$_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
if ($item->getGiftMessageId() && $_giftMessage = $_giftMessageHelper->getGiftMessage($item->getGiftMessageId())) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= __('Gift Message') ?></h3>
                        <strong><?= __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= __('Message:'); ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
<?php endif; ?>
