<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer */
?>

<?php $htmlName = 'test' ?>

<div class="tier-item">
    <div class="tier-item-price">

    </div>
</div>
<table>
    <tr>
        <td class="col-price">
            <?php if ($block->getQuote()->isCurrencyDifferent()) : ?>
                <div class="price" data-mage-init='{"currency":{"inputSelector": "<?php echo $tierItemHtmlId ?>"}}'>
                    <?php
                    echo $block->getQuote()->formatBasePricePrecision(
                        $block->getTierItem()->getBaseCustomPrice(),
                        2
                    );
                    ?>
                </div>
                <br/>
            <?php endif; ?>
            <input id="tier_item_id_<?php echo $block->getTierItem()->getId() ?>"
                   name="tierItem[<?php echo $block->getTierItem()->getId() ?>][custom_price]"
                   value="<?php echo sprintf("%.2f", $block->getTierItem()->getCustomPrice()) ?>"
                   class="input-text item-price admin__control-text"/>
        </td>
        <td class="col-qty" style="padding-left: 1rem">
            <input class="qty required-entry validate-greater-than-zero input-text"
                   type="text"
                   name="<?php /* @escapeNotVerified */ echo $htmlName ?>[<%- data.index %>][price_qty]"
                   value="1"
                   id="tier_price_row_<%- data.index %>_qty">
        </td>

        <td class="col-delete">
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $htmlName ?>[<%- data.index %>][delete]"
                   class="delete"
                   value=""
                   id="tier_price_row_<%- data.index %>_delete"/>
            <button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>"
                    type="button"
                    class="action- scalable delete icon-btn delete-product-option"
                    id="tier_price_row_<%- data.index %>_delete_button"
                    onclick="return tierPriceControl.deleteItem(event);">
            <span>
                <?php /* @escapeNotVerified */ echo __("Delete") ?>
            </span>
            </button>
        </td>
    </tr>
</table>
