<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


?>
<?php
/**
 * @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Coupons $block
 */
?>

<div class="admin__field field-apply-coupon-code">
    <label class="admin__field-label"><span><?php echo __('Apply Coupon Code') ?></span></label>

    <div class="admin__field-control">
        <input type="text" class="admin__control-text" id="coupons:code" value="" name="coupon_code"/>
        <?php echo $block->getButtonHtml(__('Apply'), 'quote.applyCoupon($F(\'coupons:code\'))') ?>
        <?php if ($block->getCouponCode()) : ?>
            <p class="added-coupon-code">
                <span><?php echo $block->escapeHtml($block->getCouponCode()) ?></span>
                <a href="#" onclick="quote.applyCoupon(''); return false;"
                   title="<?php echo __('Remove Coupon Code') ?>"
                   class="action-remove">
                    <span><?php echo __('Remove') ?></span>
                </a>
            </p>
        <?php endif; ?>
        <script>
            require(["Cart2Quote_Quotation/quote/view/form"], function () {

                quote.overlay(
                    'shipping-method-overlay',
                    <?php echo json_encode($block->getQuote()->isVirtual() ? false : true);?>
                );
                quote.overlay(
                    'address-shipping-overlay',
                    <?php echo json_encode($block->getQuote()->isVirtual() ? false : true);?>
                );
            });
        </script>
    </div>
</div>
