<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\Extra\Remark $block */
?>

<tr>
    <!-- Empty td for product description -->
    <td></td>

    <td class="col-comment" colspan="4">
        <div class="checkboxes-container">

            <!-- Optional enable/disable -->
            <div class="make-optional">
                <input type="checkbox"
                       class="admin__control-checkbox"
                       name="item[<?php echo $block->getItemId() ?>][tier_item][<?php echo $block->getTierItem()->getId() ?>][make_optional]"
                       id="make_optional_<?php echo $block->getTierItem()->getId() ?>"
                    <?php if ($block->getTierItem()->getMakeOptional()) : ?>
                        checked="checked"
                    <?php endif; ?>
                    <?php if (!$block->isActiveMakeOptional()) :?>
                        disabled="disabled"
                    <?php endif; ?> />
                <label class="normal admin__field-label"
                       for="make_optional_<?php echo $block->getTierItem()->getId() ?>">
                    <span><?php echo __('Make Optional') ?></span>
                </label>
            </div>

            <!-- Item comment enable/disable -->
            <div class="item-comment-block">
                <input type="checkbox"
                       class="admin__control-checkbox"
                       name="item[<?php echo $block->getItemId() ?>][item_has_comment]"
                       id="item_has_comment_<?php echo $block->getItemId() ?>"
                       style="<?php echo $block->getDescriptionHideInput(); ?>"
                    <?php echo $block->getDescriptionChecked(); ?>
                       onclick="quote.toggleProductRemark(
                               this,
                               'tier_item_comment_<?php echo $block->getItemId() ?>',
                               'item_tier_comment_<?php echo $block->getItemId() ?>');"/>
                <label class="normal admin__field-label"
                       for="item_has_comment_<?php echo $block->getItemId() ?>">
                    <span><?php echo __('Add Product Remark') ?></span>
                </label>
            </div>
        </div>

        <!-- Item comment -->
        <textarea id="tier_item_comment_<?php echo $block->getItemId() ?>"
                  name="item[<?php echo $block->getItemId() ?>][description]"
                  class="admin__control-textarea"
                  style="<?php echo $block->getDescriptionHideInput(); ?>"
        ><?php echo $block->escapeHtml($block->getItemDescription()) ?></textarea>
    </td>

    <!-- Add new tier item -->
    <td class="col-tier-control-add">
        <button title="<?php echo $block->escapeHtml(__('Add tier')); ?>"
                type="button"
                class="action-add-tier scalable add-tier icon-btn"
                id="tier_price_row_<%- data.index %>_add_button"
                data-mage-init='{"tierControl": {
                        "action": "addRow",
                        "itemId": <?php echo $block->getItemId() ?>,
                        "increment": 5,
                        "highestQty": <?php echo $block->getMaxTierItemQty($block->getItem()->getTierItems()); ?>
                        }}'>
            <span><?php echo __('Add Qty Tier') ?></span>
        </button>
    </td>
</tr>
