<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Info */
?>

<?php $orderViewUrls = $block->getOrderViewUrlByQuotationId($this->getQuote()->getEntityId()); ?>
<?php if ($this->getQuote()->getStatus() == 'ordered' && !empty($orderViewUrls) > 0) : ?>
    <div class="admin__page-section-item quote-linked-order">
        <?php /* Linked Orders */ ?>
        <div class="admin__page-section-item-title">
            <span class="title"><?php echo __('Linked Orders') ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-secondary quote-linked-orders-table">
                <tr>
                    <th><?php echo __('Purchase Order Number') ?></th>
                    <td>
                        <?php foreach ($orderViewUrls as $key => $val) : ?>
                            <div>
                                <a href="<?php echo $val; ?>">#<?php echo $key; ?></a>
                            </div>
                        <?php endforeach; ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php
endif;