<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block Cart2Quote\Quotation\Block\Quote\History */
?>
<?php $_quotes = $block->getQuotes(); ?>
<?php echo $block->getChildHtml('info'); ?>
<?php if ($_quotes && count($_quotes)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-quotes-table">
            <caption class="table-caption"><?php echo __('Quotes') ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?php echo __('Quote #') ?></th>
                <th scope="col" class="col date"><?php echo __('Date') ?></th>
                <th scope="col" class="col status"><?php echo __('Quote Request Status') ?></th>
                <th scope="col" class="col actions">&nbsp;</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_quotes as $_quote) : ?>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Quote #')) ?>"
                        class="col id"><?php echo $_quote->getIncrementId() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>"
                        class="col date"><?php echo $block->formatDate($_quote->getQuotationCreatedAt()) ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>"
                        class="col status"><?php echo $_quote->getStatusLabel() ?></td>
                    <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col actions">
                        <a href="<?php echo $block->getViewUrl($_quote) ?>" class="action view">
                            <span><?php echo __('View Quote') ?></span>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?php echo __('You have no quote requests.'); ?></span></div>
<?php endif ?>
