<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<?php /** @var $block \Cart2Quote\Quotation\Block\Quote\Info */ ?>
<?php $_quote = $block->getQuote() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php echo __('Quote Information') ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_quote->getIsVirtual()) : ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?php echo __('Shipping Address') ?></span></strong>

                <div class="box-content">
                    <address><?php echo $block->getFormattedAddress($_quote->getShippingAddress()); ?></address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?php echo __('Shipping Method') ?></span>
                </strong>

                <div class="box-content">
                    <?php if ($_quote->getShippingDescription()) : ?>
                        <?php echo $block->escapeHtml($_quote->getShippingDescription()) ?>
                    <?php else : ?>
                        <?php echo __('No shipping information available'); ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php echo __('Billing Address') ?></span>
            </strong>

            <div class="box-content">
                <address><?php echo $block->getFormattedAddress($_quote->getBillingAddress()); ?></address>
            </div>
        </div>
    </div>
</div>
