<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var Cart2Quote\Quotation\Block\Quote\Items $block */
?>
<?php
$_quote = $block->getQuote();
$canAccept = $_quote->canAccept();
$displayPrices = $block->isHidePrices($_quote);
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-quotes-table" summary="<?php echo __('Items Requested') ?>">
        <caption class="table-caption"><?php echo __('Items Requested') ?></caption>
        <?php foreach ($block->getSections() as $section) : ?>
            <?php $sectionsItems = $_quote->getSectionItems($section->getSectionId()); ?>
            <?php if (count($sectionsItems) > 0) : ?>
                <thead>
                <?php if (!empty($section->getLabel())) : ?>
                    <tr class="table-section">
                        <th colspan="9">
                            <h2><b><?php echo $section->getLabel(); ?></b></h2>
                        </th>
                    </tr>
                <?php endif; ?>
                <tr class="table-heading">
                    <th class="col name" colspan="3"><?php echo __('Product Name') ?></th>
                    <th class="col sku"><?php echo __('SKU') ?></th>
                    <?php if ($displayPrices) : ?>
                        <th class="col price"><?php echo __('Price') ?></th>
                    <?php endif; ?>
                    <th class="col qty"><?php echo __('Qty') ?></th>
                    <?php if ($displayPrices) : ?>
                        <th class="col subtotal"><?php echo __('Subtotal') ?></th>
                    <?php endif; ?>
                    <th class="col del">&nbsp;</th>
                    <?php if ($canAccept) : ?>
                        <th class="col tier"><?php echo __('Tier') ?></th>
                    <?php endif; ?>
                </tr>
                </thead>
                <?php foreach ($sectionsItems as $item) : ?>
                    <?php if (!$item->getParentItem()) : ?>
                        <tbody>
                        <?php echo $block->getItemHtml($item) ?>
                        </tbody>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if ($displayPrices) : ?>
            <tfoot>
            <?php echo $block->getChildHtml('quote_totals') ?>
            </tfoot>
        <?php endif; ?>
    </table>
</div>
<script>
    require([
        "jquery",
        'mage/url'
    ], function (jQuery, url) {
        jQuery("input.qty-tier:radio").change(function () {
            jQuery.ajax({
                url: url.build("quotation/quote/updatetier/quote_id/" + "<?php echo $_quote->getId()?>"),
                type: "POST",
                data: {"tier_item_id": this.value, "item_id": this.name},
                showLoader: true,
                context: jQuery(".order-details-items"),
                success: function (data) {
                    jQuery('#my-quotes-table > tfoot').html(data)
                }
            });
        });
    });
</script>