<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Cart2Quote\Quotation\Block\Quote\Sidebar */
?>
<?php if ($block->getIsQuotationEnabled()) : ?>
    <div data-block="miniquote" class="miniquote-wrapper" style="<?php echo $block->getExtraCSS(); ?>">
        <a class="action showquote" href="<?php echo $block->getQuoteCartUrl(); ?>"
           data-bind="scope: 'miniquote_content'">
            <span class="text"><?php echo __('My Quote'); ?></span>
            <span class="counter qty empty"
                  data-bind="css: { empty: quote().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: quote().summary_count --><!-- /ko --></span>
            <span class="counter-label">
            <!-- ko if: quote().summary_count -->
                <!-- ko text: quote().summary_count --><!-- /ko -->
                <!-- ko text: $t('items') --><!-- /ko -->
                <!-- /ko -->
            </span>
        </span>
        </a>
        <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
            <div class="block block-miniquote empty"
                 data-role="dropdownDialog"
                 data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=miniquote]",
                "triggerTarget":".showquote",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
                <div id="miniquote-content-wrapper" data-bind="scope: 'miniquote_content'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
        <?php endif ?>
        <script>
            window.quotation = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
        </script>
        <script type="text/x-magento-init">
        {
            "[data-block='miniquote']": {
                "Magento_Ui/js/core/app": <?php echo $block->getJsLayout(); ?>
            },
            "*": {
                "Magento_Ui/js/block-loader": "<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
            }
        }
        </script>
    </div>
<?php endif; ?>
