<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<?php /** @var  $block \Cart2Quote\Quotation\Block\Quote\View */ ?>

<?php $_history = $block->getQuote()->getVisibleStatusHistory() ?>
<?php if (count($_history)) : ?>
    <div class="block block-order-details-comments">
        <div class="block-title"><strong><?php echo __('About Your Quote') ?></strong></div>
        <div class="block-content">
            <dl class="order-comments">
                <?php foreach ($_history as $_historyItem) : ?>
                    <dt class="comment-date">
                        <?php echo $block->formatDate(
                            $_historyItem->getCreatedAtStoreDate(),
                            \IntlDateFormatter::MEDIUM,
                            true
                        ) ?>
                    </dt>
                    <dd class="comment-content"><?php echo $block->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>

        </div>
    </div>
<?php endif; ?>
