<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

?>
<div class="content" data-role="content" role="tabpanel" aria-hidden="false" style="display: block;">
    <fieldset class="fieldset estimate">
        <legend class="legend">
            <span><?php echo __('Remarks') ?></span>
        </legend>
        <br>

        <p class="field note"> <?php echo __('Do you have a general remark with this Quote Request?'); ?> </p>

        <div class="field">
            <div class="control">
                <textarea title="<?php echo __('Remarks') ?>"
                          id="quote_customer_note"
                          name="quote[customer_note]"
                          class="customer-note input-textarea"
                ><?php echo $block->escapeHtml($block->getQuote()->getCustomerNote()) ?></textarea>
            </div>
        </div>
    </fieldset>
</div>
