<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


// CS: not clear how magento would like to use that global
// @codingStandardsIgnoreFile
?>
<?php
$_quote = $block->getQuote();
$_source = $block->getSource();
$_fullInfo = $this->helper('Magento\Tax\Helper\Data')->getCalculatedTaxes($_source);
global $taxIter;
$taxIter++;
?>

<?php if ($_fullInfo && $block->displayFullSummary()) : ?><?php foreach ($_fullInfo as $info) : ?><?php
    $percent = $info['percent'];
    $amount = $info['tax_amount'];
    $baseAmount = $info['base_tax_amount'];
    $title = $info['title'];
    $planeMode = ($block->getIsPlaneMode()) ? ' plane' : '';
    ?>
    <tr class="totals tax details details-<?php echo $taxIter; ?> <?php echo $planeMode; ?>">
        <td <?php echo $block->getLabelProperties(); ?>>
            <?php echo $block->escapeHtml($title); ?>
            <?php if (!$percent !== null) : ?>
                (<?php echo (float)$percent; ?>%)
            <?php endif; ?>
            <br/>
        </td>
        <td <?php echo $block->getValueProperties() ?> rowspan="1">
            <?php echo $_quote->formatPrice($amount); ?>
        </td>
    </tr>
<?php endforeach; ?><?php endif; ?>

<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary">
    <?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary plane">
    <?php else : ?>
<tr class="totals-tax">
    <?php endif; ?>
    <th <?php echo $block->getLabelProperties(); ?> scope="row">
        <?php if ($block->displayFullSummary()) : ?>
            <div class="detailed"><?php echo __('Tax'); ?></div>
        <?php else : ?><?php echo __('Tax'); ?><?php endif; ?>
    </th>
    <td <?php echo $block->getValueProperties() ?> data-th="<?php echo $block->escapeHtml(__('Tax')); ?>">
        <?php echo $_quote->formatPrice($_source->getTaxAmount()) ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
