<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/**
 * @var \Cart2Quote\Quotation\Block\Quote\Totals $block
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total) : ?>
    <?php if ($_total->getBlockName()) : ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else : ?>
        <tr class="<?php echo $_code ?>">
            <th <?php echo $block->getLabelProperties(); ?> scope="row">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?php echo $block->escapeHtml($_total->getLabel()); ?></strong>
                <?php else : ?>
                    <?php echo $block->escapeHtml($_total->getLabel()); ?>
                <?php endif ?>
            </th>
            <td <?php echo $block->getValueProperties() ?>
                    data-th="<?php echo $block->escapeHtml($_total->getLabel()); ?>">
                <?php if ($_total->getStrong()) : ?>
                    <strong><?php echo $block->formatValue($_total) ?></strong>
                <?php else : ?>
                    <?php echo $block->formatValue($_total) ?>
                <?php endif ?>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        </tr>
    <?php endif ?>
<?php endforeach ?>
