<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */
?>
<?php
/**
 * @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer
 * @var \Cart2Quote\Quotation\Api\Data\Quote\SectionInterface[] $sections
 * @var \Cart2Quote\Quotation\Api\Data\Quote\SectionInterface $currentSection
 */
$sections = $block->getQuote()->getSections(true, ['label' => __('Not Assigned')]);
$currentSection = $block->getItem()->getExtensionAttributes()->getSection();
?>
<?php if ($block->getIsFirstTierItem()) : ?>
    <select class="admin__control-select"
            name="item[<?php echo $block->getItemId() ?>][action]" <?php echo $block->getDisabledHtml() ?>>
        <option value=""><?php echo __('Please select') ?></option>
        <option value="duplicate"><?php echo __('Duplicate Item') ?></option>
        <optgroup label="Move to section">
            <?php foreach ($sections as $section) : ?>
                <?php if ($currentSection->getSectionId() != $section->getSectionId()) : ?>
                    <option data-action="move-to-section"
                            data-name="item[<?php echo $block->getItemId() ?>][section_id]"
                            value="<?php echo $section->getSectionId() ?>">
                        <?php echo __($section->getLabel()); ?>
                    </option>
                <?php endif; ?>
            <?php endforeach; ?>
        </optgroup>
        <option value="remove"><?php echo __('Remove') ?></option>
    </select>
<?php endif; ?>