<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer */
?>

<?php if (!($block->getItem()->getProductType() == \Magento\Catalog\Model\Product\Type::TYPE_BUNDLE)) : ?>
    <?php $block->setPriceDataObject($block->getTierItem()) ?>
    <?php echo $block->displayPriceAttribute('discount_amount') ?>
    <?php if ($block->getIsSelectedTier()) : ?>
        <div class="discount-price-block">
            <input id="item_use_discount_<?php echo $block->getItemId() ?>"
                   class="admin__control-checkbox"
                   name="item[<?php echo $block->getItemId() ?>][use_discount]"
                    <?php if (!$block->getItem()->getNoDiscount()) : ?>
                       checked="checked"
                    <?php endif; ?>
                   value="1" type="checkbox"/>
            <label for="item_use_discount_<?php echo $block->getItemId() ?>"
                   class="normal admin__field-label">
                <span><?php echo __('Apply') ?></span>
            </label>
        </div>
    <?php endif; ?>
<?php else : ?>
    <?php echo $block->getChildBlock('column_discount-bundle')->setItem($block->getItem())->toHtml() ?>
<?php endif; ?>