<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\Columns\PriceQuoted */
?>
<?php
$htmlName = 'tier_item';
$tierItemHtmlId = 'tier_item_custom_price_' . $block->getTierItem()->getId();
$minPrice = $block->getMinPrice();
?>
<div class="tier-item">
    <div class="tier-item-price">
        <?php if ($block->getQuote()->isCurrencyDifferent()) : ?>
            <div class="price" data-mage-init='{"currency":{"inputSelector": "<?php echo $tierItemHtmlId ?>"}}'>
                <?php echo $block->getQuote()->formatBasePricePrecision(
                    $block->getTierItem()->getBaseCustomPrice(),
                    2
                ) ?>
            </div>
            <br/>
        <?php endif; ?>
        <input id="<?php echo $tierItemHtmlId ?>"
               name="item[<?php echo $block->getItemId() ?>][tier_item][<?php
                echo $block->getTierItem()->getId() ?>][custom_price]"
               value="<?php echo sprintf("%.2f", $block->getTierItem()->getCustomPrice()) ?>"
               class="input-text item-price admin__control-text"
               data-minprice="<?php echo $minPrice ?>"
               data-mage-init='{"priceQuoted":{}}'/>
    </div>
</div>
