<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\DefaultRenderer */
$item = $block->getItem();
$product = $item->getProduct();
$tierItem = $item->getTierItem();
?>
<?php $block->setPriceDataObject($item->getTierItem()); ?>
<?php if ($block->displayPriceExclTax() || $block->displayBothPrices()) : ?>
    <?php  ?>
    <?php if ($block->displayBothPrices()) : ?>
        <span class="label"><?php echo /* @escapeNotVerified */ __('Excl. Tax') ?>:</span>
    <?php endif; ?>
    <?php echo $block->displayPriceAttribute('original_price'); ?>
<?php endif; ?>

<?php if ($block->displayPriceInclTax() || $block->displayBothPrices()) : ?>
    <?php if ($block->displayBothPrices($block->getStore())) : ?>
        <br /><span class="label"><?php echo /* @escapeNotVerified */ __('Incl. Tax') ?>:</span>
    <?php endif; ?>
    <?php echo $block->displayPrices(
        $block->getBaseOriginalPriceInclTax($tierItem),
        $block->getOriginalPriceInclTax($tierItem)
    ); ?>
<?php endif; ?>
<?php if ($block->getIsSelectedTier() && $product->hasTierPrice() && !empty($product->getTierPrice())) :?>
    <a id="quote-view-advanced-pricing-hover">advanced pricing</a>
        <div id="quote-view-advanced-pricing" hidden>
            <?php echo __('Advanced Pricing'); ?>
            <ul>
                <li><?php echo __('Catalog price: %1', $block->formatPrice($product->getPrice())); ?></li>
                <?php foreach ($product->getTierPrice() as $advancedPrice) :?>
                    <li>
                        <?php echo __(
                            "Qty %1: %2",
                            (int)$advancedPrice['price_qty'],
                            $block->formatPrice($advancedPrice['price'])
                        ); ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
<?php endif;?>
