<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Items\Columns\Name */
?>

<?php if ($block->getIsFirstTierItem() && $item = $block->getItem()) : ?>
    <span id="quote_item_<?php echo $item->getId() ?>_title">
        <?php echo $block->escapeHtml($item->getName()) ?>
    </span>
    <div class="product-sku-block">
        <span><?php echo __('SKU') ?> :</span>
        <?php echo implode(
            '<br />',
            $block->splitSku($block->escapeHtml($block->getSku()))
        );
        ?>
    </div>
    <?php if ($block->getOrderOptions()) : ?>
        <dl class="item-options">
            <?php foreach ($block->getOrderOptions() as $_option) : ?>
                <dt>
                    <?php /* @escapeNotVerified */ echo $_option['label'] ?>:
                </dt>
                <dd>
                    <?php if (isset($_option['custom_view']) && $_option['custom_view']) : ?>
                        <?php /* @escapeNotVerified */ echo $block->getCustomizedOptionValue($_option); ?>
                    <?php else : ?>
                        <?php $_option = $block->getFormattedOption($_option['value']); ?>
                        <?php /* @escapeNotVerified */ echo $_option['value']; ?>
                        <?php if (isset($_option['remainder']) && $_option['remainder']) : ?>
                            <span id="<?php /* @escapeNotVerified */ echo $_dots = 'dots' . uniqid() ?>">
                                ...
                            </span>
                            <span id="<?php /* @escapeNotVerified */ echo $_id = 'id' . uniqid() ?>">
                                <?php /* @escapeNotVerified */ echo $_option['remainder'] ?>
                            </span>
                            <script>
                                require(['prototype'], function () {
                                    $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
                                    $('<?php /* @escapeNotVerified */
                                        echo $_id ?>').up().observe('mouseover', function () {
                                        $('<?php /* @escapeNotVerified */ echo $_id ?>').show();
                                    });
                                    $('<?php /* @escapeNotVerified */
                                        echo $_id ?>').up().observe('mouseover', function () {
                                        $('<?php /* @escapeNotVerified */ echo $_dots?>').hide();
                                    });
                                    $('<?php /* @escapeNotVerified */
                                        echo $_id ?>').up().observe('mouseout', function () {
                                        $('<?php /* @escapeNotVerified */ echo $_id ?>').hide();
                                    });
                                    $('<?php /* @escapeNotVerified */
                                        echo $_id ?>').up().observe('mouseout', function () {
                                        $('<?php /* @escapeNotVerified */ echo $_dots ?>').show();
                                    });
                                });
                            </script>
                        <?php endif; ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php echo $block->getChildBlock('column_product-bundle-items')->setItem($item)->toHtml() ?>
    <div class="product-configure-block">
        <?php echo $block->getConfigureButtonHtml($item) ?>
    </div>
<?php endif; ?>
