<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

// @codingStandardsIgnoreFile

?>

<?php /* <h4 class="icon-head fieldset-legend <?= $block->getHeaderCssClass() ?>"><?= $block->getHeaderText() ?></h4> */ ?>
<div class="admin__field field-comment">
    <label for="order-comment" class="admin__field-label"><span><?= /* @escapeNotVerified */
            __('Quote Comments') ?></span></label>
    <div class="admin__field-control">
        <textarea
                id="order-comment"
                name="order[comment][customer_note]"
                class="admin__control-textarea"><?= /* @escapeNotVerified */
            $block->getCommentNote() ?></textarea>
    </div>
</div>
<script>
    require(["Magento_Sales/order/create/form"], function () {
        order.commentFieldsBind('order-comment')
    });
</script>
