<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


/** @var $block \Cart2Quote\Quotation\Block\Adminhtml\Quote\View\Shipping\Method\Form\Quotation */ ?>

<?php $checked = $block->isMethodActive($block->getCode()) ? 'checked="checked"' : '' ?>
    <input value="<?php echo $block->getCode() ?>"
           id="s_method_<?php echo $block->getCode() ?>"
           class="admin__control-radio"
        <?php echo $checked ?>
        <?php echo $block->getRadioProperty() ?>/>
    <label class="admin__field-label" for="s_method_<?php echo $block->getCode() ?>">
        <?php echo $block->getMethodTitle() ?>
        <span id="s_method_<?php echo $block->getCode() ?>_price">-
        <strong>
            <?php $excl = $block->getShippingPrice(
                $block->getRate()->getPrice(),
                $block->getTaxHelper()->displayShippingPriceIncludingTax()
            ); ?>
            <?php $incl = $block->getShippingPrice($block->getRate()->getPrice(), true); ?>

            <?php echo $excl; ?>
            <?php if ($block->getTaxHelper()->displayShippingBothPrices() && $incl != $excl) : ?>
                (<?php echo __('Incl. Tax'); ?><?php echo $incl; ?>)
            <?php endif; ?>
        </strong>
        <a href="#"
           id="s_method_<?php echo $block->getCode() ?>_change_button"
           data-mage-init='{"shipping": {
               "selector": {
                    "input": "#s_method_<?php echo $block->getCode() ?>_input",
                    "price": "#s_method_<?php echo $block->getCode() ?>_price",
                    "submit": "#s_method_<?php echo $block->getCode() ?>_submit"
                },
                "method": "<?php echo $block->getCode() ?>"
           }}'><?php echo __('Change') ?></a>
    </span>
    </label>
    <div id="s_method_<?php echo $block->getCode() ?>_input" class="shipping-input" style="display: none;">
        <input type="number" value="<?php echo $block->getPrice(
            $block->getRate()->getPrice(),
            $block->getTaxHelper()->displayShippingPriceIncludingTax()
        ) ?>"/>
        <br/>
        <button id="s_method_<?php echo $block->getCode() ?>_submit" title="<?php echo __('Update') ?>"
                type="button"
                class="action-default scalable action-default scalable">
            <span><?php echo __('Update') ?></span>
        </button>
    </div>

<?php if ($this->getIsAjax()) : ?>
    <script type="application/javascript">
        jQuery("#s_method_<?php echo $block->getCode() ?>_change_button").trigger('contentUpdated');
    </script>
    <?php
endif;