<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


?>
<?php $_quote = $block->getQuote() ?>
<?php if ($_quote) : ?>
    <?php $_items = $_quote->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?= __('Items'); ?>
            </th>
            <th class="item-qty item-qty-last">
                <?= __('Qty'); ?>
            </th>
            <?php if (!$block->hidePrice()) : ?>
                <th class="item-price">
                    <?php echo __('Price'); ?>
                </th>
            <?php endif; ?>
        </tr>
        </thead>
        <?php foreach ($_items as $_item) : ?>
            <?php
            if ($_item->getParentItem()) {
                continue;
            }
            ?>
            <tbody>
            <?= $block->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed(
        'quote',
        $_quote,
        $_quote->getStore()
    ) && $_quote->getGiftMessageId()
    ) : ?>
        <?php
        $_giftMessageHelper = $this->helper('Magento\GiftMessage\Helper\Message');
        $_giftMessage = $_giftMessageHelper->getGiftMessage($_quote->getGiftMessageId());
        ?>
        <?php if ($_giftMessage) : ?>
            <br/>
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?= __('Gift Message for this Quote') ?></h3>
                        <strong><?= __('From:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                        <br/><strong><?= __('To:'); ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                        <br/><strong><?= __('Message:'); ?></strong>
                        <br/><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
