<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */

/** @var \Magento\Bundle\Block\Sales\Order\Items\Renderer $block */
?>
<?php $parentItem = $block->getItem() ?>
<?php $items = array_merge([$parentItem], $parentItem->getChildren()); ?>
<?php $count = count($items) ?>
<?php $index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $item) : ?>

    <?php if ($item->getOptions() || $parentItem->getDescription()) : ?>
        <?php $showlastRow = true ?>
    <?php else : ?>
        <?php $showlastRow = false ?>
    <?php endif; ?>

    <?php echo $block->getParentBlock()->getChildBlock('quotation.bundlerenderer')
        ->setItem($item)
        ->setCount($count)
        ->getChildHtml('', $useCache = false) ?>
<?php endforeach;
