<?php
/**
 *  CART2QUOTE CONFIDENTIAL
 *  __________________
 *  [2009] - [2018] Cart2Quote B.V.
 *  All Rights Reserved.
 *  NOTICE OF LICENSE
 *  All information contained herein is, and remains
 *  the property of Cart2Quote B.V. and its suppliers,
 *  if any.  The intellectual and technical concepts contained
 *  herein are proprietary to Cart2Quote B.V.
 *  and its suppliers and may be covered by European and Foreign Patents,
 *  patents in process, and are protected by trade secret or copyright law.
 *  Dissemination of this information or reproduction of this material
 *  is strictly forbidden unless prior written permission is obtained
 *  from Cart2Quote B.V.
 * @category    Cart2Quote
 * @package     Quotation
 * @copyright   Copyright (c) 2018. Cart2Quote B.V. (https://www.cart2quote.com)
 * @license     https://www.cart2quote.com/ordering-licenses(https://www.cart2quote.com)
 */


?>
<?php /** @var $block \Cart2Quote\Quotation\Block\Checkout\Cart\MoveToQuote */ ?>
<?php if ($block->getIsQuotationEnabled() && !$block->getShowOrderReferences() && $block->isMoveToQuoteEnabled()) : ?>
    <div class="cart main actions">
        <button id="movetoquote"
                type="submit"
                name="move_to_quote_action"
                value="move_to_quote"
                title="<?php echo $block->escapeHtml(__('Request a Quote')); ?>"
                class="action primary checkout movetoquote"
                data-mage-init='{"movetoquote": {"buttonSelector" : "#movetoquote"} }'>
            <span><?php echo __('Move Items to Quote'); ?></span>
        </button>
    </div>
<?php endif; ?>